server:
  port: 8080

logging:
  level:
    root: ERROR
    org.springframework.web: ERROR
    com.auth0.example: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: oAfHpyUbn7x8xmjDNIc4OwCbC7tvriyP
            client-secret: Dktak20Vpkkb4NzU3rDKVtTy8mrxk3JcU_sv8uxKZFcAFZRHS3_67UUv-kpBc_cW
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-lw8wgil5.us.auth0.com/