## YAML Template.
---
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: {client-id}
            client-secret: {client-secret}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri:  https://dev-lw8wgil5.us.auth0.com/